name: Auto Pull on Main Update

on:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Updates
        run: |
          git pull origin main
          echo "[INFO] Successfully pulled updates from main branch!"
